### ISSUE TITLE
Question: provide -j to make

### ISSUE THREAD

**Issue by mnjagadeesh** [zopefoundation/zc.recipe.cmmi#7]
Is there any way to pass -j option to `make`?
it would be great if dynamically check number of  cpu and assign to make.

Thanks in advance

**Comment by icemac** [comment]
`make` is currently called without any arguments:
https://github.com/zopefoundation/zc.recipe.cmmi/blob/f1b290883bba1d338e76f7f4d938c0d26d1a8f6d/src/zc/recipe/cmmi/__init__.py#L225

So a new option (`make-options` like the existing `configure-options`) would be needed which can be leveraged here.

A PR is welcome.

**Comment by mnjagadeesh** [comment]
https://github.com/zopefoundation/zc.recipe.cmmi/pull/8

**Comment by mnjagadeesh** [comment]
Resubmitting with test cases

**Comment by mnjagadeesh** [comment]
I have raised a PR #8 
I noticed on linux system if we can send -j parameter as environment variable. like
export MAKEFLAGS="-j 4"

**Comment by icemac** [comment]
@mnjagadeesh So your suggestion is to close the PR as the goal can be already achieved using the commandline?

**Comment by mnjagadeesh** [comment]
I am thinking if one needs to set MAKEFLAGS globally then they can set it as env variable. But my patch allows to set individually per section in buildout configuration.

**Comment by icemac** [comment]
Right, so feel free to mature your patch to make it ready to be included in the repository. See #8 for details.

**Comment by dataflake** [comment]
Feel free to reopen when you have signed the contributor agreement and fixed the test issues in #8
